// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DaemonRunning():Promise<boolean>;

export function Do(arg1:string,arg2:Record<string, string>):Promise<string>;

export function Status():Promise<string>;
