// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Ask(arg1) {
  return window['go']['main']['App']['Ask'](arg1);
}

export function AuthLogin(arg1) {
  return window['go']['main']['App']['AuthLogin'](arg1);
}

export function AuthLogout(arg1) {
  return window['go']['main']['App']['AuthLogout'](arg1);
}

export function AuthStatus(arg1) {
  return window['go']['main']['App']['AuthStatus'](arg1);
}

export function CancelListen() {
  return window['go']['main']['App']['CancelListen']();
}

export function DaemonRunning() {
  return window['go']['main']['App']['DaemonRunning']();
}

export function DeleteSecret(arg1) {
  return window['go']['main']['App']['DeleteSecret'](arg1);
}

export function Do(arg1, arg2) {
  return window['go']['main']['App']['Do'](arg1, arg2);
}

export function GUIVersion() {
  return window['go']['main']['App']['GUIVersion']();
}

export function HasSecret(arg1) {
  return window['go']['main']['App']['HasSecret'](arg1);
}

export function Hotkey() {
  return window['go']['main']['App']['Hotkey']();
}

export function Language() {
  return window['go']['main']['App']['Language']();
}

export function LanguageState() {
  return window['go']['main']['App']['LanguageState']();
}

export function Languages() {
  return window['go']['main']['App']['Languages']();
}

export function Listen() {
  return window['go']['main']['App']['Listen']();
}

export function Platform() {
  return window['go']['main']['App']['Platform']();
}

export function RestartDaemon() {
  return window['go']['main']['App']['RestartDaemon']();
}

export function SetHotkey(arg1) {
  return window['go']['main']['App']['SetHotkey'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetSecret(arg1, arg2) {
  return window['go']['main']['App']['SetSecret'](arg1, arg2);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function UpdateApply() {
  return window['go']['main']['App']['UpdateApply']();
}

export function UpdateCheck() {
  return window['go']['main']['App']['UpdateCheck']();
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
