// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DaemonRunning() {
  return window['go']['main']['App']['DaemonRunning']();
}

export function Do(arg1, arg2) {
  return window['go']['main']['App']['Do'](arg1, arg2);
}

export function GoogleLogin() {
  return window['go']['main']['App']['GoogleLogin']();
}

export function GoogleStatus() {
  return window['go']['main']['App']['GoogleStatus']();
}

export function HasSecret(arg1) {
  return window['go']['main']['App']['HasSecret'](arg1);
}

export function Listen() {
  return window['go']['main']['App']['Listen']();
}

export function Platform() {
  return window['go']['main']['App']['Platform']();
}

export function RestartDaemon() {
  return window['go']['main']['App']['RestartDaemon']();
}

export function SetSecret(arg1, arg2) {
  return window['go']['main']['App']['SetSecret'](arg1, arg2);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}
