// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthLogin(arg1:string):Promise<void>;

export function AuthLogout(arg1:string):Promise<void>;

export function AuthStatus(arg1:string):Promise<string>;

export function DaemonRunning():Promise<boolean>;

export function DeleteSecret(arg1:string):Promise<void>;

export function Do(arg1:string,arg2:Record<string, string>):Promise<string>;

export function HasSecret(arg1:string):Promise<boolean>;

export function Hotkey():Promise<string>;

export function Listen():Promise<string>;

export function Platform():Promise<string>;

export function RestartDaemon():Promise<void>;

export function SetHotkey(arg1:string):Promise<string>;

export function SetSecret(arg1:string,arg2:string):Promise<void>;

export function Status():Promise<string>;
